format = """
[](#c099ff)\
$username\
[\ue0b4](bg:#ff757f fg:#c099ff)\
$directory\
[\ue0b4](fg:#ff757f bg:#ffc777)\
$git_branch\
$git_status\
[\ue0b4](fg:#ffc777 bg:#4fd6be)\
$nodejs\
$rust\
[\ue0b4](fg:#4fd6be) \ue285 \
"""
# [ ](fg:#4fd6be)\
# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:#c099ff fg:#4c4f69"
style_root = "bg:#c099ff fg:#4c4f69"
format = '[$user ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:#c099ff"
disabled = true      # Enabled by default

[directory]
style = "bg:#ff757f fg:#4c4f69"
format = "[ $path ]($style)"
truncation_length = 1
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "


[docker_context]
symbol = " "
style = "bg:#89b4fa"
format = '[ $symbol $context ]($style) $path'

[git_branch]
symbol = ""
style = "bg:#ffc777 fg:#4c4f69"
format = '[ $symbol $branch ]($style)'
truncation_length = 10

[git_status]
style = "bg:#ffc777 fg:#4c4f69"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#4fd6be fg:#4c4f69"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:#4fd6be fg:#4c4f69"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#4fd6be fg:#4c4f69"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#4fd6be fg:#4c4f69"
format = '[ $symbol ($version) ]($style)'
version_format = "v${major}"

[rust]
symbol = ""
style = "bg:#4fd6be fg:#4c4f69"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R"              # Hour:Minute Format
style = "bg:#b4befe fg:#4c4f69"
format = '[ ♥ $time ]($style)'
