vim.g.mapleader = " "
-- vim.keymap.set("n", "<l:ader>px", vim.cmd.Ex, { desc = "Open Ex" })
vim.keymap.set("n", "<C-u>", "<C-u>zz", { desc = "page up and center" })
vim.keymap.set("n", "<C-d>", "<C-d>zz", { desc = "page down and center" })
vim.keymap.set("n", "n", "nzzv", { desc = "find next and center" })
vim.keymap.set("n", "N", "Nzzv", { desc = "find prev and center" })
vim.keymap.set("n", "<leader>w", ":w<cr>", { desc = "Save file" })
-- vim.keymap.set("i", "<C-k>", "<Esc>:w<cr>i", { desc = "Save file" })
vim.keymap.set("n", "<leader>bn", ":bnext<cr>", { desc = "Next Buffer" })
vim.keymap.set("n", "<leader>bp", ":bprev<cr>", { desc = "Prev Buffer" })
vim.keymap.set("n", "<leader>e", ":Neotree toggle<cr>", { desc = "Toggle Nvim Tree" })
-- vim.keymap.set("n", "<leader>s", ":NvimTreeFindFile<cr>", { desc = "Show file in Nvim Tree" })
vim.keymap.set("n", "<leader>i", "<C-i>", { desc = "jump forward" })
vim.keymap.set("n", "<leader>o", "<C-o>", { desc = "jump backward" })
vim.keymap.set("n", "<leader>s", ":lua require('toggle-bool').toggle_bool()<cr>", { desc = "toggle" })
vim.keymap.set("i", "<c-e>", "<c-o>", { desc = "special insert mode" })

vim.keymap.set('n', '<leader>y', [[:let @+ = getline('.')<CR>]], { noremap = true, silent = true })
vim.keymap.set('n', '<leader>p', '"+p', { noremap = true, silent = true })
